# Generated by Django 2.2 on 2019-05-12 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyTypeName', models.CharField(max_length=100)),
                ('propertyTypeDescription', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponValue', models.DecimalField(decimal_places=2, max_digits=3)),
                ('couponName', models.CharField(max_length=100)),
                ('couponDescription', models.CharField(max_length=250)),
                ('couponType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.CouponType')),
            ],
        ),
    ]
