# Generated by Django 2.2 on 2019-05-12 03:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestateapp', '0002_coupon_propertytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=225)),
                ('amenity_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('neighborhood_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighborhood_name', models.CharField(max_length=225)),
                ('neighborhood_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_file', models.URLField()),
                ('photo_added_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyAddress', models.CharField(max_length=100)),
                ('propertyCreatedDate', models.DateField()),
                ('propertyMarketPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('propertyDescription', models.CharField(max_length=512)),
                ('propertySqFt', models.IntegerField()),
                ('propertyBedrooms', models.IntegerField()),
                ('propertyBathrooms', models.IntegerField()),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.Neighborhood')),
                ('propertyType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.PropertyType')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Photo',
            fields=[
                ('property_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.Photo')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Amenity',
            fields=[
                ('property_amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.Amenity')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('offerDate', models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 11, 20, 8, 22, 662826))),
                ('propertyBuilding', models.ManyToManyField(to='realestateapp.Property')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
