# Generated by Django 2.2 on 2019-05-12 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0003_amenity_neighborhood_offer_photo_property_property_amenity_property_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 11, 20, 12, 53, 659652)),
        ),
    ]
