# Generated by Django 2.2 on 2019-05-12 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0004_auto_20190511_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupontype',
            name='couponTypeName',
            field=models.CharField(default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 12, 15, 15, 15, 327466)),
        ),
    ]
