# Generated by Django 2.2 on 2019-05-14 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0006_auto_20190512_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerCounter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerCounterDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 1, 0, 24, 400606)),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyCreatedDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 1, 0, 24, 400606)),
        ),
    ]
