# Generated by Django 2.2 on 2019-05-14 09:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestateapp', '0006_auto_20190512_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=30)),
                ('roleDescription', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 14, 2, 9, 8, 869801)),
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPicture', models.ImageField(blank=True, default='user_pics/None/no-img.jpg', upload_to='user_pics/')),
                ('userDesc', models.TextField(blank=True, default='This user has no description yet.', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginDate', models.DateTimeField(default=datetime.datetime.now)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.Role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownershipBeginDate', models.DateTimeField(default=datetime.datetime.now)),
                ('ownershipEndDate', models.DateTimeField(blank=True, null=True)),
                ('ownershipAskingPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ownershipPaidPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.Coupon')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.Property')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartAddedDate', models.DateTimeField(default=datetime.datetime.now)),
                ('cartRemovedDate', models.DateTimeField(blank=True, null=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestateapp.Property')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
