# Generated by Django 2.2 on 2019-05-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0007_auto_20190514_0100'),
        ('realestateapp', '0007_auto_20190514_0209'),
    ]

    operations = [
    ]
