# Generated by Django 2.2.1 on 2019-05-14 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0007_auto_20190514_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 14, 20, 9, 28, 596335)),
        ),
    ]
