# Generated by Django 2.2 on 2019-05-14 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0008_merge_20190514_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='couponDescription',
            field=models.CharField(blank=True, default='Generic coupon.', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='couponName',
            field=models.CharField(default='Generic', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='couponValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='coupontype',
            name='couponTypeDescription',
            field=models.CharField(blank=True, default='Not specified.', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='coupontype',
            name='couponTypeName',
            field=models.CharField(default='General', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 13, 46, 29, 305982)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_added_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyAddress',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyCreatedDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 13, 46, 29, 304985)),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyDescription',
            field=models.CharField(blank=True, default='', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyMarketPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, unique=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='propertyTypeDescription',
            field=models.CharField(blank=True, default='Not classified property', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='propertyTypeName',
            field=models.CharField(default='Unclassified', max_length=50, unique=True),
        ),
    ]
