# Generated by Django 2.2.1 on 2019-05-14 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0009_auto_20190514_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerCounterAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerCounterDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 14, 22, 48, 53, 698050)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 14, 22, 48, 53, 698016)),
        ),
    ]
