# Generated by Django 2.2.1 on 2019-05-14 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0010_auto_20190514_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerCounterAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerCounterDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 14, 22, 50, 32, 393148)),
        ),
    ]
