# Generated by Django 2.2 on 2019-05-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0008_auto_20190514_2009'),
        ('realestateapp', '0010_auto_20190514_1353'),
    ]

    operations = [
    ]
