# Generated by Django 2.2.1 on 2019-05-14 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0011_auto_20190514_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerCounterDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 14, 22, 51, 15, 997128)),
        ),
    ]
