# Generated by Django 2.2 on 2019-05-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0012_auto_20190514_2251'),
        ('realestateapp', '0011_merge_20190514_1601'),
    ]

    operations = [
    ]
