# Generated by Django 2.2 on 2019-05-14 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0013_merge_20190514_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offerCounter',
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerCounterDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 14, 16, 7, 17, 914050)),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyCreatedDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 16, 7, 17, 913053)),
        ),
    ]
