# Generated by Django 2.2 on 2019-05-14 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0014_auto_20190514_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 14, 16, 24, 52, 497416)),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyCreatedDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 16, 24, 52, 497416)),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleDescription',
            field=models.CharField(choices=[('AD', 'Administrative controls'), ('SE', 'Sells properties'), ('US', 'General user')], default='USER', max_length=6),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleName',
            field=models.CharField(choices=[('AD', 'ADMIN'), ('SE', 'SELLER'), ('US', 'USER')], default='USER', max_length=6),
        ),
    ]
