# Generated by Django 2.2 on 2019-05-15 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0017_auto_20190514_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 14, 17, 15, 29, 961372)),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyCreatedDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 17, 15, 29, 960377)),
        ),
    ]
