# Generated by Django 2.2 on 2019-06-06 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0018_auto_20190514_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 5, 18, 15, 38, 946396)),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyAddress',
            field=models.CharField(default='Address not given', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyCreatedDate',
            field=models.DateField(default=datetime.datetime(2019, 6, 5, 18, 15, 38, 942175)),
        ),
    ]
