# Generated by Django 2.2 on 2019-06-06 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0021_auto_20190605_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livability',
            fields=[
                ('livability_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('score', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 5, 23, 11, 32, 111946)),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyCreatedDate',
            field=models.DateField(default=datetime.datetime(2019, 6, 5, 23, 11, 32, 111946)),
        ),
    ]
