# Generated by Django 2.2 on 2019-06-06 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0023_auto_20190605_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 5, 23, 22, 17, 715541)),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyCreatedDate',
            field=models.DateField(default=datetime.datetime(2019, 6, 5, 23, 22, 17, 714544)),
        ),
    ]
