# Generated by Django 2.2 on 2019-06-06 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0024_auto_20190605_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livability',
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 6, 0, 37, 0, 409383)),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyCreatedDate',
            field=models.DateField(default=datetime.datetime(2019, 6, 6, 0, 37, 0, 408386)),
        ),
    ]
