# Generated by Django 2.2 on 2019-06-06 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0025_auto_20190606_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyLivability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 6, 0, 42, 13, 384137)),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyCreatedDate',
            field=models.DateField(default=datetime.datetime(2019, 6, 6, 0, 42, 13, 384137)),
        ),
    ]
