# Generated by Django 2.2.1 on 2019-06-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0026_auto_20190606_0042'),
        ('realestateapp', '0022_auto_20190606_0753'),
    ]

    operations = [
    ]
